import type { Metadata } from 'next'
import { Inter as FontSans } from 'next/font/google'

import MainLayout from '@/components/layouts/MainLayout'
import { cn } from '@/lib/utils'
import { Toaster } from 'sonner'
import './globals.css'

export const fontSans = FontSans({
	subsets: ['latin'],
	variable: '--font-sans',
})

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default function RootLayout({
	children,
}: {
	children: React.ReactNode
}) {
	return (
		<html lang="en">
			<body
				className={cn(
					'min-h-screen font-sans antialiased dark',
					fontSans.variable
				)}
			>
				<MainLayout>{children}</MainLayout>
                <Toaster />
			</body>
		</html>
	)
}
